apiVersion: v1
kind: Pod
metadata:
  name: mathapp
  labels:
    app: mathapp
spec:
  containers:
    - name: mathapp
      image: mathapp:v1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mathapp
spec:
  type: NodePort
  selector:
    app: mathapp
  ports:
    - port: 3010
      targetPort: 8080
      nodePort: 31000