apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathapp
spec:
  selector:
    matchLabels:
      app: mathapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mathapp
    spec:
      containers:
        - name: mathapp
          image: mathapp:v1
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: mathapp
spec:
  type: NodePort
  selector:
    app: mathapp
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    # you can add more ports to a single service with '-'
    - port: 3010
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31000
      protocol: TCP